spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: spring_life
  data:
    redis:
      database: 0
      host: 172.16.3.88
      #      host: 127.0.0.1
      port: 32379
      #      port: 6379
      password: Deta2020
      timeout: 0
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8888   #sentinel控制台的请求地址
server:
  port: 8888

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
